namespace PlantToXmi.EAAddin.Update
{
    public enum UpdateResultCode
    {
        NO_UPDATE_AVAILABLE,
        UPDATE_AVAILABLE,
        UPDATE_INSTALLED,
        UPDATE_FAILED_NETWORK,
        UPDATE_FAILED_MANIFEST_MISSING,
        UPDATE_FAILED_MANIFEST_INVALID,
        UPDATE_FAILED_ASSET_MISSING,
        UPDATE_FAILED_HASH_MISMATCH,
        UPDATE_FAILED_EXTRACT,
        UPDATE_FAILED_SMOKE_TEST,
        BOOTSTRAPPER_UPGRADE_REQUIRED,
        ROLLBACK_COMPLETED,
        ROLLBACK_FAILED
    }
}
